name: ci

on:
  push:
    branches:
      - master
    tags:
      - '*'
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 12.x
      - name: Build
        run: |
          yarn
          yarn build
      - name: Test
        run: |
          yarn build:test
          # yarn test
      - name: Docs
        run: |
          yarn docs
